//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriSpending1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class declineSpending
    {
        public int declineId { get; set; }
        public int spendingId { get; set; }
        public string declineTitle { get; set; }
        public string declineComment { get; set; }
    
        public virtual spending spending { get; set; }
    }
}
