//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriSpending1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public System.Guid logId { get; set; }
        public string userId { get; set; }
        public string ıpAddres { get; set; }
        public string areaAccessed { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string browser { get; set; }
    }
}
